[pytest]
addopts = -s -v --alluredir=reports/allure-results
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: 冒烟测试
    regression: 回归测试
    user: 用户模块
    post: 文章模块
